<?php
/**
 * @var $this Bubble_Api_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('http://i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/jreinke/magento-improve-api" target="_blank" style="float:right;">
            <img src="http://i.imgur.com/QVKwCFx.png" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('bubble_api')->__('Bubble Api improves default features of Magento API such as association of simple products and configurable products.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('bubble_api')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('bubble_api')->__('http://www.bubblecode.net/en/2012/04/20/magento-api-associate-simple-products-to-configurable-or-grouped-product/')); ?>" target="_blank"><?php echo $this->helper('bubble_api')->__('here'); ?></a>.</p>
    </div>
</div>